camel:
  server-port: 5000
  springboot:
    main-run-controller: true
    dataformat:
      json-jackson:
        auto-discover-object-mapper: true


application:
  bucket-name: paymenthub-ee-dev

zeebe:
  client:
    max-execution-threads: 1000
    evenly-allocated-max-jobs: 1000
    #    max-execution-threads: 100
    #    number-of-workers: 8
    #    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "zeebe-zeebe-gateway:26500"

operations-app:
  contactpoint: "https://ops-bk.ibank.financial"
  endpoints:
    batch-transaction: "/api/v1/batch/transactions"

cloud:
  aws:
    enabled: true
    credentials:
      access-key: ${AWS_ACCESS_KEY:AKIAX32JM37TZOJ5AKFB}
      secret-key: ${AWS_SECRET_KEY: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}
    region:
      static: us-east-2
    stack:
      auto: false
  azure:
    enabled: false
    blob:
      connection-string:


tenants: "ibank-usa,ibank-india"

bpmn:
  flows:
    payment-transfer: "PayerFundTransfer-{dfspid}"
    transaction-request: "PayeeTransactionRequest-{dfspid}"
    party-registration: "PartyRegistration-{dfspid}"
    gsma-base-transaction: "gsma_base_transaction-{dfspid}"
    gsma-int-transfer: "gsma_int_transfer-{dfspid}"
    gsma-payee-process: "gsma_payee_process"
    gsma-bill-payment: "gsma_bill_payment"
    gsma-link-based-payment: "gsma_link_transfer"
    international-remittance-payee: "international_remittance_payee_process-{dfspid}"
    international-remittance-payer: "international_remittance_payer_process-{dfspid}"
    debit-party-process: "debit_party_process-{dfspid}"
    bulk-processor: "bulk_processor-ibank-usa"
    slcb: "slcb-{dfspid}"

config:
  minimum-successful-tx-ratio: 0.90
  partylookup:
    enable: true
  approval:
    enable: true
  ordering:
    enable: false
    field: "payment_mode"
  splitting:
    enable: false
    sub-batch-size: 5
  formatting:
    enable: false
    standard: "DEFAULT"
  mergeback:
    enable: false
  backpressure:
    enable: false
  success-threshold-check:
    enable: false
    success-rate: 95 # in percentage

template:
  types:
    - id: "PROGRAM"
      metadata: "cycle,program_shortcode"
    - id: "MOJALOOP"
      metadata: "payer_identifier_type,payer_identifier,payee_identifier_type,payee_identifier"
